SiteTree:
  extensions:
    - GlobalNavExtension
GlobalNav:
  hostname: 'http://ssorg-another.test.silverstripe.com'
  snippet_path: '/global_nav.html'
Director:
  routes:
    'toolbar//$Action': 'GlobalToolbarController'
